### ISSUE TITLE
Status page down 

### ISSUE THREAD

**Issue by pke** [keedrop/keedrop#85]
404 on status.keedrop.com

**Comment by pke** [comment]
I have an uptimerobot pro account we could use if required.

**Comment by milgner** [comment]
That would be appreciated... would that make your account more expensive? Because I saw that the custom domain status pages aren't free anymore but I didn't want to pay any money just for that. But if you already have an account where it could run under existing capacity then that would be nice.
Alternatively I'll set up a static page somewhere with a free tier, maybe S3, with a redirect only.
